// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/features/search/data/datasources/search_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_app/core/models/movie_details_model/movie_details_model.dart'
    as _i3;
import 'package:movies_app/core/models/movies_model/movies_model.dart' as _i2;
import 'package:movies_app/core/services/api/api_service.dart' as _i6;
import 'package:movies_app/features/show_movies/data/models/movie_cast_model/movie_cast_model.dart'
    as _i4;
import 'package:movies_app/features/show_movies/data/models/movie_reviews_model/movie_reviews_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMoviesModel_0 extends _i1.SmartFake implements _i2.MoviesModel {
  _FakeMoviesModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailsModel_1 extends _i1.SmartFake
    implements _i3.MovieDetailsModel {
  _FakeMovieDetailsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieCastModel_2 extends _i1.SmartFake
    implements _i4.MovieCastModel {
  _FakeMovieCastModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieReviewsModel_3 extends _i1.SmartFake
    implements _i5.MovieReviewsModel {
  _FakeMovieReviewsModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.MoviesModel> getMoviesByCategory({
    required String? category,
    required int? page,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMoviesByCategory, [], {
              #category: category,
              #page: page,
              #language: language,
            }),
            returnValue: _i7.Future<_i2.MoviesModel>.value(
              _FakeMoviesModel_0(
                this,
                Invocation.method(#getMoviesByCategory, [], {
                  #category: category,
                  #page: page,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.MoviesModel>);

  @override
  _i7.Future<_i2.MoviesModel> getRandomeMovies({
    required int? page,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomeMovies, [], {
              #page: page,
              #language: language,
            }),
            returnValue: _i7.Future<_i2.MoviesModel>.value(
              _FakeMoviesModel_0(
                this,
                Invocation.method(#getRandomeMovies, [], {
                  #page: page,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.MoviesModel>);

  @override
  _i7.Future<_i3.MovieDetailsModel> getMovieDetails({
    required int? movieId,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [], {
              #movieId: movieId,
              #language: language,
            }),
            returnValue: _i7.Future<_i3.MovieDetailsModel>.value(
              _FakeMovieDetailsModel_1(
                this,
                Invocation.method(#getMovieDetails, [], {
                  #movieId: movieId,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.MovieDetailsModel>);

  @override
  _i7.Future<_i4.MovieCastModel> getMovieCast({
    required int? movieId,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieCast, [], {
              #movieId: movieId,
              #language: language,
            }),
            returnValue: _i7.Future<_i4.MovieCastModel>.value(
              _FakeMovieCastModel_2(
                this,
                Invocation.method(#getMovieCast, [], {
                  #movieId: movieId,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.MovieCastModel>);

  @override
  _i7.Future<_i5.MovieReviewsModel> getMovieReviews({
    required int? movieId,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieReviews, [], {
              #movieId: movieId,
              #language: language,
            }),
            returnValue: _i7.Future<_i5.MovieReviewsModel>.value(
              _FakeMovieReviewsModel_3(
                this,
                Invocation.method(#getMovieReviews, [], {
                  #movieId: movieId,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.MovieReviewsModel>);

  @override
  _i7.Future<_i2.MoviesModel> searchMovies({
    required String? query,
    required int? page,
    required _i8.CancelToken? cancelToken,
    String? language = 'en-US',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [], {
              #query: query,
              #page: page,
              #cancelToken: cancelToken,
              #language: language,
            }),
            returnValue: _i7.Future<_i2.MoviesModel>.value(
              _FakeMoviesModel_0(
                this,
                Invocation.method(#searchMovies, [], {
                  #query: query,
                  #page: page,
                  #cancelToken: cancelToken,
                  #language: language,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.MoviesModel>);
}
