// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/features/auth/presentation/managers/phone_auth_cubit/phone_auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:movies_app/core/utils/response_result.dart' as _i4;
import 'package:movies_app/features/auth/domain/usecases/send_code_use_case.dart'
    as _i2;
import 'package:movies_app/features/auth/domain/usecases/verify_code_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SendCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendCodeUseCase extends _i1.Mock implements _i2.SendCodeUseCase {
  MockSendCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResponseResult<String>> call(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#call, [phoneNumber]),
            returnValue: _i3.Future<_i4.ResponseResult<String>>.value(
              _i5.dummyValue<_i4.ResponseResult<String>>(
                this,
                Invocation.method(#call, [phoneNumber]),
              ),
            ),
          )
          as _i3.Future<_i4.ResponseResult<String>>);
}

/// A class which mocks [VerifyCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyCodeUseCase extends _i1.Mock implements _i6.VerifyCodeUseCase {
  MockVerifyCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResponseResult<String>> call(
    String? verificationId,
    String? smsCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [verificationId, smsCode]),
            returnValue: _i3.Future<_i4.ResponseResult<String>>.value(
              _i5.dummyValue<_i4.ResponseResult<String>>(
                this,
                Invocation.method(#call, [verificationId, smsCode]),
              ),
            ),
          )
          as _i3.Future<_i4.ResponseResult<String>>);
}
