// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/features/auth/data/repositories/facebook_auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_facebook_auth/flutter_facebook_auth.dart' as _i3;
import 'package:flutter_facebook_auth_platform_interface/flutter_facebook_auth_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResult_0 extends _i1.SmartFake implements _i2.LoginResult {
  _FakeLoginResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FacebookAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacebookAuth extends _i1.Mock implements _i3.FacebookAuth {
  MockFacebookAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccessToken?> get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i4.Future<_i2.AccessToken?>.value(),
          )
          as _i4.Future<_i2.AccessToken?>);

  @override
  bool get isWebSdkInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSdkInitialized),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> get isAutoLogAppEventsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoLogAppEventsEnabled),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.LoginResult> expressLogin() =>
      (super.noSuchMethod(
            Invocation.method(#expressLogin, []),
            returnValue: _i4.Future<_i2.LoginResult>.value(
              _FakeLoginResult_0(this, Invocation.method(#expressLogin, [])),
            ),
          )
          as _i4.Future<_i2.LoginResult>);

  @override
  _i4.Future<Map<String, dynamic>> getUserData({
    String? fields = 'name,email,picture.width(200)',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [], {#fields: fields}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> logOut() =>
      (super.noSuchMethod(
            Invocation.method(#logOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.LoginResult> login({
    List<String>? permissions = const ['email', 'public_profile'],
    _i2.LoginBehavior? loginBehavior = _i2.LoginBehavior.nativeWithFallback,
    _i2.LoginTracking? loginTracking = _i2.LoginTracking.limited,
    String? nonce,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #permissions: permissions,
              #loginBehavior: loginBehavior,
              #loginTracking: loginTracking,
              #nonce: nonce,
            }),
            returnValue: _i4.Future<_i2.LoginResult>.value(
              _FakeLoginResult_0(
                this,
                Invocation.method(#login, [], {
                  #permissions: permissions,
                  #loginBehavior: loginBehavior,
                  #loginTracking: loginTracking,
                  #nonce: nonce,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.LoginResult>);

  @override
  _i4.Future<void> webAndDesktopInitialize({
    required String? appId,
    required bool? cookie,
    required bool? xfbml,
    required String? version,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#webAndDesktopInitialize, [], {
              #appId: appId,
              #cookie: cookie,
              #xfbml: xfbml,
              #version: version,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> autoLogAppEventsEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#autoLogAppEventsEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
