// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/core/services/shared_preferences/shared_preferences_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_app/core/services/shared_preferences/shared_preferences_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i2.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setString({required String? key, required String? value}) =>
      super.noSuchMethod(
        Invocation.method(#setString, [], {#key: key, #value: value}),
        returnValueForMissingStub: null,
      );

  @override
  void setBool({required String? key, required bool? value}) =>
      super.noSuchMethod(
        Invocation.method(#setBool, [], {#key: key, #value: value}),
        returnValueForMissingStub: null,
      );

  @override
  void setList({required String? key, required List<String>? value}) =>
      super.noSuchMethod(
        Invocation.method(#setList, [], {#key: key, #value: value}),
        returnValueForMissingStub: null,
      );

  @override
  String? getString({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#getString, [], {#key: key}))
          as String?);

  @override
  bool? getBool({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#getBool, [], {#key: key}))
          as bool?);

  @override
  List<String> getList({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#getList, [], {#key: key}),
            returnValue: <String>[],
          )
          as List<String>);
}
