// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/features/show_movies/presentation/managers/movie_details_cubit/movie_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:movies_app/core/utils/response_result.dart' as _i4;
import 'package:movies_app/features/show_movies/domain/entities/movie_cast_entity.dart'
    as _i8;
import 'package:movies_app/features/show_movies/domain/entities/movie_details_entity.dart'
    as _i5;
import 'package:movies_app/features/show_movies/domain/entities/movie_reviews_entity.dart'
    as _i10;
import 'package:movies_app/features/show_movies/domain/usecases/get_movie_cast_use_case.dart'
    as _i7;
import 'package:movies_app/features/show_movies/domain/usecases/get_movie_details_use_case.dart'
    as _i2;
import 'package:movies_app/features/show_movies/domain/usecases/get_movie_reviews_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetMovieDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetailsUseCase extends _i1.Mock
    implements _i2.GetMovieDetailsUseCase {
  MockGetMovieDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResponseResult<_i5.MovieDetailsEntity>> call({
    required int? movieId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#movieId: movieId}),
            returnValue:
                _i3.Future<_i4.ResponseResult<_i5.MovieDetailsEntity>>.value(
                  _i6.dummyValue<_i4.ResponseResult<_i5.MovieDetailsEntity>>(
                    this,
                    Invocation.method(#call, [], {#movieId: movieId}),
                  ),
                ),
          )
          as _i3.Future<_i4.ResponseResult<_i5.MovieDetailsEntity>>);
}

/// A class which mocks [GetMovieCastUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieCastUseCase extends _i1.Mock
    implements _i7.GetMovieCastUseCase {
  MockGetMovieCastUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResponseResult<List<_i8.MovieCastEntity>>> call({
    required int? movieId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#movieId: movieId}),
            returnValue:
                _i3.Future<_i4.ResponseResult<List<_i8.MovieCastEntity>>>.value(
                  _i6.dummyValue<_i4.ResponseResult<List<_i8.MovieCastEntity>>>(
                    this,
                    Invocation.method(#call, [], {#movieId: movieId}),
                  ),
                ),
          )
          as _i3.Future<_i4.ResponseResult<List<_i8.MovieCastEntity>>>);
}

/// A class which mocks [GetMovieReviewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieReviewsUseCase extends _i1.Mock
    implements _i9.GetMovieReviewsUseCase {
  MockGetMovieReviewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResponseResult<List<_i10.MovieReviewsEntity>>> call({
    required int? movieId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#movieId: movieId}),
            returnValue:
                _i3.Future<
                  _i4.ResponseResult<List<_i10.MovieReviewsEntity>>
                >.value(
                  _i6.dummyValue<
                    _i4.ResponseResult<List<_i10.MovieReviewsEntity>>
                  >(this, Invocation.method(#call, [], {#movieId: movieId})),
                ),
          )
          as _i3.Future<_i4.ResponseResult<List<_i10.MovieReviewsEntity>>>);
}
