// Mocks generated by Mockito 5.4.6 from annotations
// in movies_app/test/features/search/data/repositories/search_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_app/core/models/movies_model/movies_model.dart' as _i2;
import 'package:movies_app/features/search/data/datasources/search_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMoviesModel_0 extends _i1.SmartFake implements _i2.MoviesModel {
  _FakeMoviesModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDataSource extends _i1.Mock implements _i3.SearchDataSource {
  MockSearchDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MoviesModel> searchMovies({
    required String? query,
    required int? page,
    required _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [], {
              #query: query,
              #page: page,
              #cancelToken: cancelToken,
            }),
            returnValue: _i4.Future<_i2.MoviesModel>.value(
              _FakeMoviesModel_0(
                this,
                Invocation.method(#searchMovies, [], {
                  #query: query,
                  #page: page,
                  #cancelToken: cancelToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MoviesModel>);
}
